name: JAR

on: 
  push:
    branches:
    - master
    paths:
      - 'chrome/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create an updated chrome/SubjectManager.jar file
      run: |
         cd chrome
         zip SubjectManager.jar content/* locale/* skin/* 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add chrome/SubjectManager.jar
        git commit -m "SubjectManager.jar created" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
